/**
 * 用户管理
 */
//y用户登录
export const USER_LOGIN = 'USER_LOGIN'
export const USER_EXIT = 'USER_EXIT'
//首页 index 用户统计
export const GETUSERAMOUNT = 'GETUSERAMOUNT'
//首页 index 店铺统计
export const GETSHOPAMOUNT = 'GETSHOPAMOUNT'
//首页 index 入驻申请
export const GETCOMPANYAMOUNT = 'GETCOMPANYAMOUNT'
//首页 index 实名认证
export const GETAUDITUSERAMOUT = 'GETAUDITUSERAMOUT'
//首页 index 举报统计
export const GETREPORTAMOUNT = 'GETREPORTAMOUNT'
//类目管理
export const QUERYCATEGORY = 'QUERYCATEGORY'//行业增加
export const GETINDUSTRY_URL = 'GET_INDUSTRY'
export const GET_PARENT_CATEGORY = 'GET_PARENT_CATEGORY'//弗雷姆
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY'
export const EDITCATEGORY_URL = 'EDIT_CATAGORY'
//店铺管理
export const GETSHOP_URL = 'GETSHOP_URL'
export const GETSHOPDETAILS_URL = 'GETSHOPDETAILS_URL'
export const CLOSESHOP_URL = 'CLOSESHOP_URL'
export const STARTSHOP_URL = 'STARTSHOP_URL'
export const DELETESHOP_URL = 'DELETESHOP_URL'
//商家管理
export const BUSINESSMANAGER = 'BUSINESSMANAGER'
export const GETPAYEDSHOP = 'GETPAYEDSHOP'
//公司认证
export const GETCOMPANYBASIC_URL = 'GET_COMPANY_BASIC'
//公司认证获取基本信息
export const JUDGECOMPANY_URL = 'JUDGECOMPANY_URL'
//实名认证
export const GETREALNAME_URL = 'GETREALNAME_URL'
export const JUDGEREALNAME_URL = 'JUDGEREALNAME_URL'
//头像认证
export const GETAVATARUSER = 'GETAVATARUSER'
export const JUDGEAVATAR = 'JUDGEAVATAR'
//海报认证
export const GETCOVERUSER ='GETCOVERUSER'
export const JUDGECOVER = 'JUDGECOVER'
/**
 * 路由管理
 */
//举报列表
export const GETREPORTLIST1 = 'GETREPORTLIST1'
export const GETREPORTLIST2 = 'GETREPORTLIST2'
//举报的表处理
export const JUDGEREPORT = 'JUDGEREPORT'
//举报列表的删除
export const DELETEREPORT = 'DELETEREPORT'
export const CHANGEPLANTFORMHOMEFITMENT = 'CHANGEPLANTFORMHOMEFITMENT'
export const GETPLATFORORMHOMEFITMENT = 'GETPLATFORORMHOMEFITMENT'
export const SAVE_ROUTER = 'SAVE_ROUTER'
//发布
export const PUBLISHPLANT = 'PUBLISHPLANT'
//下拉菜单
export const GETOPTION_URL = 'GETOPTION_URL'
//商品品类
export const GETGOODSSORT ='GETGOODSSORT'
export const GETGOODSSORTS ='GETGOODSSORTS'
//商品品类提交
export const UPDATEGOODS = 'UPDATEGOODS'
export const QUERY_QINIU_UPLOADTOKEN = 'QUERY_QINIU_UPLOADTOKEN'
//
export const GETREFUNDORDERSSHENHE = 'GETREFUNDORDERSSHENHE'
export const GETREFUNDORDERSDAIDAKUAN = 'GETREFUNDORDERSDAIDAKUAN'
export const GETREFUNDORDERSYIDAKUAN = 'GETREFUNDORDERSYIDAKUAN'
export const JUDGEREFUNDORDER = 'JUDGEREFUNDORDER'
export const DELETEREFUNDORDER = 'DELETEREFUNDORDER'
//商友圈广告
export const GETSNSPOSTER = 'GETSNSPOSTER'
export const UPDATESNSPOSTER = 'UPDATESNSPOSTER'
//上传七牛
// export const UPLOADER_BUSINESS_LICENCE = 'UPLOADER_BUSINESS_LICENCE'
export const GETIMAGEPATH = 'GETIMAGEPATH'
export const DRAWWITH_URL = 'DRAWWITH_URL'//提现-------------------